routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\admin\CompanyController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
    // return view('layouts.admin');
});

Auth::routes();

Route::get('/admin/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/companies', CompanyController::class);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $table="companies";
    protected $fillable=([
        'id','name','owner','phone','email','address','location','logo','is_active','user_id'
    ]);

}

app/Http/Controllers/admin/CompanyController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\User;
use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use phpDocumentor\Reflection\Types\Nullable;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=[];
        $data['companies']=Company::get();

        // dd($data['companies']);

        return view('admin.companies.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    //    dd($request->all());
    // $this->validate($request, [
    //     'name' => 'required|string|max:250',
    //     'phone' => 'required|string|max:191',
    //     'address' => 'required',
    //     'email' => 'required|string|email|max:191|unique:users',
    //     'password' => 'required|string|min:6|confirmed',
    //     'image' => 'nullable|image|max:5120',
    // ]);

    $ImageName='profile.png';
    if ($request->hasFile('image')){
       $image = $request->file('image');
       $ImageName = time().'.'.$image->getClientOriginalExtension();
       Image::make($image)->resize(400, 400)->save(base_path('public/uploads/companies/').$ImageName);
    }

    $user = new User();
    $user->name = $request->name;
    $user->email = $request->email;
    $user->password = Hash::make($request->password);
    $user->user_type = 'Company';
    $user->phone = $request->phone;
    $user->image = 'companies/'.$ImageName;
    $user->save();
// dd($user);
    $company = new Company();
    $company->user_id = $user->id;
    $company->name=$request->name;
    $company->owner=$request->owner;
    $company->email=$request->email;
    $company->phone=$request->phone;
    $company->address=$request->address;
    $company->logo = 'companies/'.$ImageName;
    $company->is_active=$request->is_active==true?1:0;

    $company->save();

    return redirect('admin/companies')->with('success', 'Add Successfull !');
    // return back();



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.companies.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::findOrFail($id);
        // dd($company);
        $data['company']=Company::findOrFail($id);
        // dd($company);
        return view('admin.companies.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::findOrFail($id);
       // $company->user_id = $user->id;

       $ImageName=null;
       if ($request->hasFile('image')){
          $image = $request->file('image');
          $ImageName = time().'.'.$image->getClientOriginalExtension();
          Image::make($image)->resize(400, 400)->save(base_path('public/uploads/companies/').$ImageName);
          unlink(base_path('public/uploads/'.$company->logo));
          $company->logo = 'companies/'.$ImageName;
        }else{
            $company->logo = $company->logo;
       }


        $company->name=$request->name;
        $company->owner=$request->owner;
        $company->email=$request->email;
        $company->phone=$request->phone;
        $company->address=$request->address;
        $company->is_active=$request->is_active==true?1:0;

        $company->save();


        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.admin')
@section('title','Company List')
@push('css_style')
<link rel="stylesheet" href="{{asset('backend/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}" />
@endpush

@section('content')

<div class="card">
    <div class="card-body">
      <h4 class="card-title">Create Company</h4>
      <p class="card-description">
        Please fill the information of company
      </p>
      <form class="forms-sample form-horizontal form-groups-bordered" action="{{route('companies.store')}}" method="post" enctype="multipart/form-data" >
            @csrf

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="company">Company Name</label>
                        <input type="text" name="name" class="form-control" id="company" placeholder="Company Name">

                    </div>
                    <div class="form-group">
                        <label for="owner">Owner</label>
                        <input type="text" name="owner" class="form-control" id="owner" placeholder="Company Name">
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Company Name">
                    </div>

                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                    </div>

                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" name="address" class="form-control" id="address" placeholder="Company Name">
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group">
						<label class="col-sm-3 control-label">Company Logo</label>
						<div class="col-sm-9">
							<input type="file" class="form-control dropify" name="image" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG">
						</div>

					</div>

                    <div class="form-group">
                        <div class="form-check form-check-flat">
                            <label class="form-check-label">
                            <input type="checkbox" name="is_active" class="form-check-input">
                            Is Active?
                            <i class="input-helper"></i></label>
                        </div>
                    </div>

                </div>

            </div>

            <button type="submit" class="btn btn-success mr-2">Save</button>
            <a class="btn btn-light" href="{{route('companies.index')}}">Cancel</a>
      </form>
    </div>
  </div>

@endsection


@push('script_js')
  <!-- Plugin js for this page-->
  <script src="{{asset('backend/vendors/datatables.net/jquery.dataTables.js')}}"></script>
  <script src="{{asset('backend/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
  <script src="{{asset('backend/js/data-table.js')}}"></script>
@endpush

resources/views/admin/companies/edit.blade.php
@extends('layouts.admin')
@section('title','Company List')
@push('css_style')
<link rel="stylesheet" href="{{asset('backend/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}" />
@endpush

@section('content')

<div class="card">
    <div class="card-body">
      <h4 class="card-title">Edit Company</h4>

      <form class="forms-sample form-horizontal form-groups-bordered" action="{{route('companies.update',$company->id)}}" method="post" enctype="multipart/form-data" >
            {{-- @csrf --}}
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="company">Company Name</label>
                        <input type="text" name="name" class="form-control" id="company" placeholder="Company Name" value="{{$company->name}}">

                    </div>
                    <div class="form-group">
                        <label for="owner">Owner</label>
                        <input type="text" name="owner" class="form-control" id="owner" placeholder="Company Owner" value="{{$company->owner}}">
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Company Phone" value="{{$company->phone}}">
                    </div>

                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Email" value="{{$company->email}}">
                    </div>
                    {{-- <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password" >
                    </div> --}}

                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" name="address" class="form-control" id="address" placeholder="Company Address" value="{{$company->address}}">
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group">
						<label class="col-sm-3 control-label">Company Logo</label>
						<div class="col-sm-9">
							<input type="file" class="form-control dropify" name="image" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="{{asset('uploads/'.$company->logo)}}">
						</div>

					</div>

                    <div class="form-group">
                        <div class="form-check form-check-flat">
                            <label class="form-check-label">
                            <input type="checkbox" name="is_active" class="form-check-input" {{$company->is_active==1?'checked':''}}>
                            Is Active?
                            <i class="input-helper"></i></label>
                        </div>
                    </div>

                </div>

            </div>

            <button type="submit" class="btn btn-success mr-2">Upate</button>
            <a class="btn btn-light" href="{{route('companies.index')}}">Cancel</a>
      </form>
    </div>
  </div>

@endsection


@push('script_js')
  <!-- Plugin js for this page-->
  <script src="{{asset('backend/vendors/datatables.net/jquery.dataTables.js')}}"></script>
  <script src="{{asset('backend/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
  <script src="{{asset('backend/js/data-table.js')}}"></script>
@endpush

resources/views/admin/companies/index.blade.php
@extends('layouts.admin')
@section('title','Company List')
@push('css_style')
    <link rel="stylesheet" href="{{asset('backend/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}" />
 <!-- SweetAlert2 -->
 <link rel="stylesheet" href="{{asset('backend/sweetalert2/sweetalert2.min.css') }}">
    @endpush


@section('content')


<div class="card">
    <div class="card-body">

      <h4 class="card-title">Company List  <a class="btn btn-primary btn-sm pull-right ajax-modal" href="{{route('companies.create')}}">Create</a></h4>
      <div class="row">
        <div class="col-12">
          <div class="table-responsive">
            <table id="order-listing" class="table">
              <thead>
                <tr>
                    <th>ID #</th>
                    <th>Comapny Name</th>
                    <th>Owner</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($companies as $row)
                <tr>
                    <td>{{$row->id}}</td>
                    <td>
                        <div class="wrapper d-flex align-items-center py-2 border-bottom">
                            <img class="img-sm rounded-circle" src="{{asset('uploads/'. $row->logo)}}" alt="profile">
                            <div class="wrapper ml-3">
                                <h6 class="ml-1 mb-1"> {{$row->name}}</h6>
                                <small class="text-muted mb-0"><i class="mdi mdi-map-marker-outline mr-1"></i>{{$row->address}}</small>
                            </div>
                            <div class="badge badge-pill badge-info ml-auto px-1 py-1"><i class="mdi mdi-check font-weight-bold"></i></div>
                        </div>



                    </td>
                    <td>{{$row->owner}}</td>
                    <td>{{$row->phone}}</td>
                    <td>{{$row->email}}</td>
                    <td>{{$row->address}}</td>
                    <td>
                      <label class="badge badge-info">On hold</label>
                    </td>


                    <td class="text-center">
                        <a href="{{ route('companies.edit',$row->id) }}" class="badge badge-danger">
                            <i class="mdi mdi-pencil"></i> Edit
                        </a>
                        <a href="javascript:deleteItem({{ $row->id }})" class="badge badge-info" id="btnDelete">
                            <i class="mdi mdi-delete"></i> Delete
                        </a>
                        <form id="frmDeleteItem-{{ $row->id }}" style="display: none" action="{{ route('companies.destroy',$row->id) }}" role="form" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                        </form>
                    </td>
                </tr>
                @endforeach

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>


@endsection


@push('script_js')

 <!-- SweetAlert2 -->
 <script src="{{asset('backend/sweetalert2/sweetalert2.min.js') }}"></script>

  <!-- Plugin js for this page-->
  <script src="{{asset('backend/vendors/datatables.net/jquery.dataTables.js')}}"></script>
  <script src="{{asset('backend/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
  <script src="{{asset('backend/js/data-table.js')}}"></script>

  <script  src="{{asset('backend/js/script.js')}}"></script>


  <script type="text/javascript">
    function deleteItem(id){
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          document.getElementById('frmDeleteItem-'+id).submit();
          Swal.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          )
        }
      })
    }
</script>

@endpush