routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\admin\CompanyController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
    // return view('layouts.admin');
});

Auth::routes();

Route::get('/admin/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/companies', CompanyController::class);

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
}

app/Models/MenuType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuType extends Model
{
    use HasFactory;
}

resources/views/layouts/menus/Admin.blade.php
<li class="nav-item">
    <a class="nav-link" href="{{url('/admin/home')}}">
    <i class="icon-rocket menu-icon"></i>
    <span class="menu-title">Dashboard</span>
    <span class="badge badge-success">New</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" data-toggle="collapse" href="#tables1" aria-expanded="false" aria-controls="tables">
    <i class="fa fa-address-book-o menu-icon"></i>
    <span class="menu-title">All People</span>
    <span class="badge badge-info">4</span>
    </a>
    <div class="collapse" id="tables1">
    <ul class="nav flex-column sub-menu">
        <li class="nav-item"> <a class="nav-link" href="{{route('companies.index')}}">Companies</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Delivers</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Venders</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Categories</a></li>
    </ul>
    </div>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{url('/admin/home')}}">
        <i class="fa fa-id-badge menu-icon"></i>
        <span class="menu-title">Customers</span>
        <span class="badge badge-info">4</span>
    </a>
</li>



{{-- Users --}}

<li class="nav-item">
    <a class="nav-link" href="{{url('#')}}">
        <i class="fa fa-group menu-icon"></i>
        <span class="menu-title">Manage Users</span>
        <span class="badge badge-info">4</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{url('#')}}">
        <i class="fa fa-cogs menu-icon"></i>
        <span class="menu-title">Settings</span>
        <span class="badge badge-info">4</span>
    </a>
</li>

resources/views/layouts/menus/Company.blade.php
<li class="nav-item">
    <a class="nav-link" href="{{url('/admin/home')}}">
    <i class="icon-rocket menu-icon"></i>
    <span class="menu-title">Dashboard</span>
    <span class="badge badge-success">New</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" data-toggle="collapse" href="#tables1" aria-expanded="false" aria-controls="tables">
    <i class="fa fa-car menu-icon"></i>
    <span class="menu-title">Delivery Company</span>
    <span class="badge badge-info">4</span>
    </a>
    <div class="collapse" id="tables1">
    <ul class="nav flex-column sub-menu">
        <li class="nav-item"> <a class="nav-link" href="{{route('companies.index')}}">Company List</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Delivers List</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Customer List</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Income</a></li>
    </ul>
    </div>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{url('/admin/home')}}">
        <i class="fa fa-id-badge menu-icon"></i>
        <span class="menu-title">Customers</span>
        <span class="badge badge-info">4</span>
    </a>
</li>

resources/views/layouts/menus/Deliver.blade.php
<li class="nav-item">
    <a class="nav-link" href="{{url('/admin/home')}}">
    <i class="icon-rocket menu-icon"></i>
    <span class="menu-title">Dashboard</span>
    <span class="badge badge-success">New</span>
    </a>
</li>

{{-- <li class="nav-item">
    <a class="nav-link" data-toggle="collapse" href="#tables1" aria-expanded="false" aria-controls="tables">
    <i class="fa fa-car menu-icon"></i>
    <span class="menu-title">Delivery Company</span>
    <span class="badge badge-info">4</span>
    </a>
    <div class="collapse" id="tables1">
    <ul class="nav flex-column sub-menu">
        <li class="nav-item"> <a class="nav-link" href="{{route('companies.index')}}">Company List</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Delivers List</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Customer List</a></li>
        <li class="nav-item"> <a class="nav-link" href="#">Income</a></li>
    </ul>
    </div>
</li> --}}

<li class="nav-item">
    <a class="nav-link" href="{{url('/admin/home')}}">
        <i class="fa fa-id-badge menu-icon"></i>
        <span class="menu-title">Customers</span>
        <span class="badge badge-info">4</span>
    </a>
</li>